# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: FTP Deployer
        # You may pin to the exact commit or the version.
        # uses: sand4rt/ftp-deployer@23eeee83b7ee23d5355f7c1b72bd003aea371f59
        uses: sand4rt/ftp-deployer@v1.1
        with:
          # FTP host URL like: ftp.host.com
          host: ${{secrets.FTP_SERVER}}
          # FTP port
          port: # optional, default is 21
          # Ftp username
          username: ${{secrets.FTP_USER}}
          # Ftp password
          password: ${{secrets.FTP_PASSWORD}} 
          # The remote folder location of your FTP server
          remote_folder: /dev/laravel-vue# optional
          # The local folder location
          local_folder: # optional, default is dist
          # Remove existing files inside FTP remote folder
          cleanup: # optional
          # includes
          include: # optional
          # exclude
          exclude: # optional
          # passive
          pasive: # optional
